# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestEmptyCart():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_emptycart(self):
        self.driver.get("https://63580b0bc4fa9.site123.me//shop-1/white-ceramic-plate")
        self.driver.find_element(By.XPATH, "(//*[contains(text(),'Add To Cart')])[1]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//*[contains(text(),'Make an order')]").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navActions:nth-child(2) .svg-m").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//*[@class ='btn btn-sm btn-link empty-cart']").click()
        cart_container = self.driver.find_element(By.XPATH, '//*[@id="cartOrderPage"]/div/div[2]/div[2]/div[1]/h1')
        cart = cart_container.get_attribute('innerText')
        assert "Your shopping cart is empty" in cart



