# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMakeAnOrder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_makeanorder(self):
    self.driver.get("https://63580b0bc4fa9.site123.me//shop-1/white-ceramic-plate")
    self.driver.find_element(By.XPATH, "(//*[contains(text(),'Add To Cart')])[1]").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//*[contains(text(),'Make an order')]").click()
    order_page = self.driver.find_element(By.XPATH, '//*[@id="section--title"]')
    order_page_title = order_page.get_attribute('innerText')
    assert "COMPLETE YOUR ORDER" in order_page_title


