# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestIncrementshopitem():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_incrementshopitem(self):
        # Test name: increment shop item
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://63580b0bc4fa9.site123.me//shop-1/white-ceramic-plate")
        # find the add to cart button
        self.driver.find_element(By.XPATH, "(//*[contains(text(),'Add To Cart')])[1]").click()
        #  click make an order after the wait time for side drawer
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//*[contains(text(),'Make an order')]").click()
        # click cart button
        self.driver.find_element(By.CSS_SELECTOR, ".navActions:nth-child(2) .svg-m").click()
        time.sleep(2)
        qty_element = self.driver.find_element(By.CLASS_NAME, "qty_count")
        old_qty = int(qty_element.get_attribute("innerText"))
        # increase quantity by 1
        self.driver.find_element(By.XPATH, "//*[@class='edit-quantity-button edit-quantity-plus']").click()

        qty = int(qty_element.get_attribute("innerText"))
        print(qty)
        assert qty == old_qty + 1
