# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContactPage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contactpage(self):
    self.driver.get("https://63580b0bc4fa9.site123.me/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "#top-menu .moduleMenu:nth-child(4) .txt-container").click()
    contact_page = self.driver.find_element(By.XPATH, '//*[@id="section-5addd1414c9a8-title"]')
    contact_page_title = contact_page.get_attribute('innerText')
    assert "CONTACT" in contact_page_title

  
